// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Ambienti documents */
interface AmbientiDocumentData {
    /**
     * Nome Ambiente field in *Ambienti*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: ambienti.nome_ambiente
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    nome_ambiente: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Ambienti*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: ambienti.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<AmbientiDocumentDataSlicesSlice>;
}
/**
 * Slice for *Ambienti → Slice Zone*
 *
 */
type AmbientiDocumentDataSlicesSlice = ImmaginiSlice;
/**
 * Ambienti document from Prismic
 *
 * - **API ID**: `ambienti`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AmbientiDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AmbientiDocumentData>, "ambienti", Lang>;
export type AllDocumentTypes = AmbientiDocument;
/**
 * Item in Immagini → Items
 *
 */
export interface ImmaginiSliceDefaultItem {
    /**
     * Foto field in *Immagini → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: immagini.items[].foto
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    foto: prismicT.ImageField<never>;
}
/**
 * Default variation for Immagini Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Immagini`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImmaginiSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ImmaginiSliceDefaultItem>>;
/**
 * Slice variation for *Immagini*
 *
 */
type ImmaginiSliceVariation = ImmaginiSliceDefault;
/**
 * Immagini Shared Slice
 *
 * - **API ID**: `immagini`
 * - **Description**: `Immagini`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImmaginiSlice = prismicT.SharedSlice<"immagini", ImmaginiSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AmbientiDocumentData, AmbientiDocumentDataSlicesSlice, AmbientiDocument, AllDocumentTypes, ImmaginiSliceDefaultItem, ImmaginiSliceDefault, ImmaginiSliceVariation, ImmaginiSlice };
    }
}
