import type { NextPage } from "next";
import Head from "next/head";
import HeroSection from "./HeroSection";
import Navbar from "../Components/Navbar";
import ChiSiamo from "./ChiSiamo";
import Progetti from "./Progetti";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tweetter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HeroSection />
      <ChiSiamo />
      <Progetti />
    </div>
  );
};

export default Home;
