import type { NextPage } from "next";
import Head from "next/head";
import HeroSection from "./sections/HeroSection";
import Navbar from "../components/layout/Navbar";
import ChiSiamo from "./sections/ChiSiamo";
import Contatti from "./sections/Contatti";
import Progetti from "./sections/Progetti";
import Footer from "../components/layout/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Falegnameria Mancini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HeroSection />
      <ChiSiamo />
      <Progetti />
      <Contatti />
      <Footer />
    </div>
  );
};

export default Home;
